package ru.maxizenit.footballleaguemanager.gui.dialog.entitydialog;

import com.github.lgooddatepicker.components.DatePicker;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.springframework.data.convert.Jsr310Converters.DateToLocalDateConverter;
import org.springframework.data.convert.Jsr310Converters.LocalDateToDateConverter;
import ru.maxizenit.footballleaguemanager.entity.Match;
import ru.maxizenit.footballleaguemanager.entity.Team;
import ru.maxizenit.footballleaguemanager.exception.InvalidFieldException;

/**
 * Диалог для матчей.
 */
public class MatchDialog extends EntityDialog<Match> {

  private JPanel mainPanel;

  private JButton buttonOK;

  private JButton buttonCancel;

  private DatePicker dateField;

  /**
   * Поле домашней команды.
   */
  private JComboBox<Team> homeTeamField;

  /**
   * Поле гостевой команды.
   */
  private JComboBox<Team> guestTeamField;

  public MatchDialog(JFrame parent, SaveFunction<Match> saveFunction,
      RefreshGUIFunction refreshGUIFunction, Match entity, List<Team> teams) {
    super(parent, saveFunction, refreshGUIFunction, entity);
    initCombos(teams);
    init(mainPanel, buttonOK, buttonCancel);
    pack();
    setVisible(true);
  }

  /**
   * Инициализирует комбинированные списки для полей команд.
   *
   * @param teams список команд
   */
  private void initCombos(List<Team> teams) {
    DefaultComboBoxModel<Team> homeTeamFieldModel = new DefaultComboBoxModel<>();
    homeTeamFieldModel.addAll(teams);
    homeTeamField.setModel(homeTeamFieldModel);

    DefaultComboBoxModel<Team> guestTeamFieldModel = new DefaultComboBoxModel<>();
    guestTeamFieldModel.addAll(teams);
    guestTeamField.setModel(guestTeamFieldModel);
  }

  @Override
  protected void fillFields(Match entity) {
    dateField.setDate(DateToLocalDateConverter.INSTANCE.convert(entity.getDate()));
    homeTeamField.setSelectedItem(entity.getHomeTeam());
    guestTeamField.setSelectedItem(entity.getGuestTeam());
  }

  @Override
  protected boolean isFieldsValid() throws InvalidFieldException {
    List<String> invalidFields = new ArrayList<>();

    if (dateField.getDate() == null) {
      invalidFields.add("дата");
      throw new InvalidFieldException(invalidFields);
    }

    return true;
  }

  @Override
  protected Match createNewEntity() {
    return new Match();
  }

  @Override
  protected void fillEntityFromFields(Match entity) {
    entity.setDate(LocalDateToDateConverter.INSTANCE.convert(dateField.getDate()));
    entity.setHomeTeam((Team) homeTeamField.getSelectedItem());
    entity.setGuestTeam((Team) guestTeamField.getSelectedItem());
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
    mainPanel.add(panel1, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    buttonOK = new JButton();
    buttonOK.setText("ОК");
    panel1.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    buttonCancel = new JButton();
    buttonCancel.setText("Отмена");
    panel1.add(buttonCancel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label1 = new JLabel();
    label1.setText("Дата");
    mainPanel.add(label1,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
            false));
    final JLabel label2 = new JLabel();
    label2.setText("Домашняя команда");
    mainPanel.add(label2,
        new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
            false));
    final JLabel label3 = new JLabel();
    label3.setText("Гостевая команда");
    mainPanel.add(label3,
        new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
            false));
    dateField = new DatePicker();
    mainPanel.add(dateField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
        null, 0, false));
    homeTeamField = new JComboBox();
    mainPanel.add(homeTeamField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST,
        GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    guestTeamField = new JComboBox();
    mainPanel.add(guestTeamField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST,
        GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }
}
